AllCops:
  TargetRubyVersion: 2.6.2
  NewCops: enable
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - ./*/spec/**/*

Metrics/MethodLength:
  Max: 30
  Exclude:
    - spec/dummy/db/**/*
    - ./*/spec/**/*

Metrics/ClassLength:
  Max: 270
Metrics/AbcSize:
  Max: 35
Metrics/CyclomaticComplexity:
  Max: 10

Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Security/YAMLLoad:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  MinSize: 3
Style/WordArray:
  MinSize: 3
Style/MixinUsage:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - spec/**/*
Style/NumericPredicate:
  Enabled: false
Style/DoubleNegation:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/Encoding:
  Enabled: false

Layout/LineLength:
  Exclude:
    - spec/**/*
    - ./*/spec/**/*
  Max: 100

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true
